# Check README.md for how to format this file
banners:
- name: (URB-24) HMRC banner - Guidance CXD 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Working_for_yourself
  page_paths:
    # frontend
    - /working-for-yourself
  start_date: 2025/12/01
  end_date: 2026/01/19
- name: (URB-24) HMRC banner - Guidance CXD 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Check_additional_income_tax
  page_paths:
    # frontend
    - /check-additional-income-tax
  start_date: 2025/12/01
  end_date: 2026/01/19
- name: (URB-24) HMRC banner - Guidance CXD 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Tell_HMRC_about_income_from_online_platforms
  page_paths:
    # frontend
    - /guidance/check-if-you-need-to-tell-hmrc-about-your-income-from-online-platforms
  start_date: 2025/12/01
  end_date: 2026/01/19
- name: (URB-24) HMRC banner - Guidance CXD 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Tell_HMRC_new_job_or_more_than_one_job
  page_paths:
    # frontend
    - /guidance/tell-hmrc-if-you-have-a-new-job-or-more-than-one-job
  start_date: 2025/12/01
  end_date: 2026/01/19
- name: (URB-20) HMRC banner - Manuals 2025/12/09
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://forms.office.com/e/c4LPez4F25?origin=lprLink
  page_paths:
    # government-frontend
    - /hmrc-internal-manuals/partnership-manual
    - /hmrc-internal-manuals/partnership-manual/pm134200
    - /hmrc-internal-manuals/partnership-manual/pm137000
  start_date: 2025/12/09
  end_date: 2026/01/06
- name: (URB-19) HMRC banner - Guidance CXD 2025/12/08
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Check_Employment_Status
  page_paths:
    # frontend
    - /guidance/check-employment-status-for-tax
  start_date: 2025/12/08
  end_date: 2026/02/02
- name: (URB-23) HMRC banner - Guidance CXD 2025/12/11
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CEST_contracts_conditions
  page_paths:
    # frontend
    - /employment-contracts-and-conditions
  start_date: 2025/12/11
  end_date: 2026/02/05
- name: (URB-23) HMRC banner - Guidance CXD 2025/12/11
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CEST_Construction
  page_paths:
    # frontend
    - /what-is-the-construction-industry-scheme
  start_date: 2025/12/11
  end_date: 2026/02/05
- name: (URB-23) HMRC banner - Guidance CXD 2025/12/11
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CEST_limited_company_rules
  page_paths:
    # frontend
    - /employment-agencies-and-businesses/limited-company-contractors-and-opting-out-of-the-rules
  start_date: 2025/12/11
  end_date: 2026/02/05
- name: (URB-23) HMRC banner - Guidance CXD 2025/12/11
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CEST_recruiting
  page_paths:
    # collections
    - /browse/employing-people/recruiting-hiring
  start_date: 2025/12/11
  end_date: 2026/02/05
- name: (URB-23) HMRC banner - Guidance CXD 2025/12/11
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CEST_Employer_responsibilities
  page_paths:
    # frontend
    - /contract-types-and-employer-responsibilities
  start_date: 2025/12/11
  end_date: 2026/02/05
- name: (URB-27) HMRC banner - Flat Rate Scheme 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_MTD_VAT_Flat_rate_scheme
  page_paths:
    # frontend
    - /vat-flat-rate-scheme
    - /vat-flat-rate-scheme/leaving-the-scheme
    - /vat-flat-rate-scheme/if-your-circumstances-change
    - /guidance/flat-rate-scheme-for-small-businesses-vat-notice-733--2
  start_date: 2025/12/15
  end_date: 2026/01/12
- name: (URB-27) HMRC banner - Reporting 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_MTD_VAT_Reporting
  page_paths:
    # frontend
    - /charge-reclaim-record-vat
    - /charge-reclaim-record-vat/when-not-to-charge-vat
  start_date: 2025/12/15
  end_date: 2026/01/12
- name: (URB-27) HMRC banner - Misc Banner 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_MTD_VAT_Misc
  page_paths:
    # frontend
    - /guidance/vat-exemption-and-partial-exemption
    - /guidance/partial-exemption-vat-notice-706
    - /guidance/vat-how-to-work-out-your-place-of-supply-of-services
    - /guidance/vat-place-of-supply-of-services-notice-741a
  start_date: 2025/12/15
  end_date: 2026/01/12
- name: (URB-27) HMRC banner - Registration 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_MTD_VAT_Registration
  page_paths:
    # frontend
    - /government/publications/vat-notice-7001-should-i-be-registered-for-vat/vat-notice-7001-should-i-be-registered-for-vat
  start_date: 2025/12/15
  end_date: 2026/01/12
- name: (URB-27) HMRC banner - Deregistration 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_MTD_VAT_De-registration
  page_paths:
    # frontend
    - /register-for-vat/cancel-your-registration  
  start_date: 2025/12/15
  end_date: 2026/01/12
- name: (URB-27) HMRC banner - Payments 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_MTD_VAT_Payments
  page_paths:
    # frontend
    - /pay-vat
    - /pay-vat/direct-debit
    - /pay-vat/pay-using-another-payment-method
    - /guidance/vat-payments-on-account
    - /guidance/vat-imports-acquisitions-and-purchases-from-abroad
    - /guidance/how-late-payment-penalties-work-if-you-pay-vat-late
  start_date: 2025/12/15
  end_date: 2026/01/12
- name: (URB-26) HMRC banner - Policy 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Off_Payroll_Working_Agencies
  page_paths:
    # frontend
    - /guidance/off-payroll-working-for-agencies
  start_date: 2025/12/18
  end_date: 2026/01/15
- name: (URB-26) HMRC banner - Policy 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Understanding_Off_Payroll_Working_In_IR35
  page_paths:
    # frontend
    - /guidance/understanding-off-payroll-working-ir35
  start_date: 2025/12/18
  end_date: 2026/01/15
- name: (URB-26) HMRC banner - Policy 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Off_Payroll_Working_Rules
  page_paths:
    # frontend
    - /guidance/fee-payer-responsibilities-under-the-off-payroll-working-rules
  start_date: 2025/12/18
  end_date: 2026/01/15
- name: (URB-26) HMRC banner - Policy 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Off_Payroll_Working_For_Intermediaries_And_Contractors
  page_paths:
    # frontend
    - /guidance/off-payroll-working-for-intermediaries-and-contractors-providing-services-to-small-clients-in-the-private-sector
  start_date: 2025/12/18
  end_date: 2026/01/15
- name: (URB-26) HMRC banner - Policy 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Off_Payroll_Working_For_Intermediaries_And_Contractors_Private_Sector_Medium_Large_Clients
  page_paths:
    # frontend
    - /guidance/off-payroll-working-for-intermediaries-and-contractors-providing-services-to-the-public-sector-or-medium-and-large-clients-in-the-private-sector
  start_date: 2025/12/18
  end_date: 2026/01/15
- name: (URB-26) HMRC banner - Policy 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Check_Employment_Status_Hair_and_Beauty
  page_paths:
    # frontend
    - /guidance/check-employment-status-if-you-work-in-hair-and-beauty
  start_date: 2025/12/18
  end_date: 2026/01/15
- name: (URB-26) HMRC banner - Policy 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Off_Payroll_Working_IR35_Detailed_Information
  page_paths:
    # frontend
    - /government/collections/off-payroll-working-ir35-detailed-information
  start_date: 2025/12/18
  end_date: 2026/01/15
- name: (URB-26) HMRC banner - Policy 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Employed_or_Self_Employed
  page_paths:
    # frontend
    - /government/collections/employed-or-self-employed
  start_date: 2025/12/18
  end_date: 2026/01/15
- name: (URB-28) HMRC banner 2026/01/05
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CT_Guidance_TAD
  page_paths:
    # frontend
    - /pay-corporation-tax
    - /file-your-company-accounts-and-tax-return
    - /running-a-limited-company
    - /running-a-limited-company/taking-money-out-of-a-limited-company
    - /corporation-tax-rates
    - /guidance/company-expenses-you-can-deduct-before-paying-corporation-tax
    # collections
    - /set-up-limited-company
    # smartanswers
    - /next-steps-for-your-business
  start_date: 2026/01/05
  end_date: 2026/02/02
- name: (URB-29) HMRC banner 2026/01/05
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Partnerships2_TAD
  page_paths:
    # frontend
    - /guidance/register-a-partner-for-self-assessment-and-class-2-national-insurance
    - /government/publications/self-assessment-partnership-tax-return-sa800
    - /guidance/changes-to-reporting-income-from-self-employment-and-partnerships
    - /government/publications/self-assessment-partnership-uk-property-sa801
    - /guidance/register-a-partner-for-self-assessment-if-theyre-not-an-individual
  start_date: 2026/01/05
  end_date: 2026/02/02
- name: (URB-25) AI banner 2026/01/09
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://surveys.publishing.service.gov.uk/s/ST7P6Y/
  page_paths:
    # frontend
    - /what-different-qualification-levels-mean/list-of-qualification-levels
    - /child-maintenance-service
    - /photos-for-passports
    - /fishing-licences
    - /carers-allowance
    - /jobseekers-allowance
    - /settled-status-eu-citizens-families
    - /school-term-holiday-dates
    - /universal-credit
    - /foreign-travel-advice/spain
    # collections
    - /government/organisations/land-registry
    - /government/organisations/department-for-work-pensions
    - /browse/business
    - /browse/childcare-parenting
    - /browse/disabilities
    - /browse/education
    - /browse/employing-people
    - /browse/environment-countryside
    - /browse/housing-local-services
  start_date: 2026/01/09
  end_date: 2026/01/30
