# Check README.md for how to format this file
banners:
- name: HMRC banner - Simple Assessment PAYE CI Request 25/10/17
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Tax_On_Pension
  page_paths:
    # frontend
    - /tax-on-pension
  start_date: 2025/10/17
  end_date: 2025/12/12
- name: HMRC banner - Simple Assessment PAYE CI Request 25/10/17
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Check_Simple_Assessment
  page_paths:
    # frontend
    - /check-simple-assessment
  start_date: 2025/10/17
  end_date: 2025/12/12
- name: HMRC banner - Simple Assessment PAYE CI Request 25/10/17
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Simple_Assessment
  page_paths:
    # frontend
    - /simple-assessment
  start_date: 2025/10/17
  end_date: 2025/12/12
- name: HMRC banner - Simple Assessment PAYE CI Request 25/10/17
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Apply_Tax_Free_Interest_On_Savings
  page_paths:
    # frontend
    - /apply-tax-free-interest-on-savings
  start_date: 2025/10/17
  end_date: 2025/12/12
- name: HMRC banner - CXD Guidance 2025/10/20
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Tax_Compliance_Checks
  page_paths:
    # frontend
    - /tax-compliance-checks
  start_date: 2025/10/20
  end_date: 2025/12/08
- name: HMRC banner - CXD Guidance 2025/10/20
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Get_Help_If_HMRC_Contacts_You_About_A_Compliance_Check
  page_paths:
    # frontend
    - /guidance/get-help-if-hmrc-contacts-you-about-a-compliance-check
  start_date: 2025/10/20
  end_date: 2025/12/08
- name: HMRC banner - CXD Guidance 2025/10/20
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_HMRC_Compliance_Checks_Help_And_Support
  page_paths:
    # frontend
    - /guidance/hmrc-compliance-checks-help-and-support
  start_date: 2025/10/20
  end_date: 2025/12/08
- name: HMRC banner - CXD Guidance 2025/10/20
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Guidelines_For_Compliance
  page_paths:
    # frontend
    - /government/collections/guidelines-for-compliance
  start_date: 2025/10/20
  end_date: 2025/12/08
- name: HMRC banner - CXD Guidance 2025/10/20
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Paying_HMRC_Detailed_Information
  page_paths:
    # frontend
    - /government/collections/paying-hmrc-detailed-information
  start_date: 2025/10/20
  end_date: 2025/12/08
- name: HMRC banner - CXD Guidance 2025/11/20
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Partnerships2_TAD
  page_paths:
    # frontend
    - /set-up-business-partnership
    - /set-up-business-partnership/register-partnership-with-hmrc
    - /guidance/register-a-partnership-for-self-assessment
    - /guidance/register-a-partner-for-self-assessment-and-class-2-national-insurance
    - /government/publications/self-assessment-partnership-full-sa104f
    - /government/publications/self-assessment-partnership-uk-property-sa801
    - /government/publications/self-assessment-partnership-tax-return-sa800
  start_date: 2025/11/20
  end_date: 2025/12/25
- name: (URB-22) HMRC banner - CXD CY 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_cyfrif-treth-personol&Q_Language=CY
  page_paths:
    # frontend
    - /cyfrif-treth-personol
  start_date: 2025/12/01
  end_date: 2025/12/29
- name: (URB-22) HMRC banner - CXD CY 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_mewngofnodi-cofrestru-gwasanaethau-ar-lein-cthef&Q_Language=CY
  page_paths:
    # frontend
    - /mewngofnodi-cofrestru-gwasanaethau-ar-lein-cthef
  start_date: 2025/12/01
  end_date: 2025/12/29
- name: (URB-22) HMRC banner - CXD CY 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_treth-incwm-hunanasesiad-a-mwy&Q_Language=CY
  page_paths:
    # frontend
    - /find-hmrc-contacts/treth-incwm-hunanasesiad-a-mwy
  start_date: 2025/12/01
  end_date: 2025/12/29
- name: (URB-22) HMRC banner - CXD CY 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_cyfrif-gofal-plant&Q_Language=CY
  page_paths:
    # frontend
    - /mewngofnodi-ir-cyfrif-gofal-plant
  start_date: 2025/12/01
  end_date: 2025/12/29
- name: (URB-22) HMRC banner - CXD CY 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_download-the-hmrc-app.cy&Q_Language=CY
  page_paths:
    # frontend
    - /guidance/download-the-hmrc-app.cy
  start_date: 2025/12/01
  end_date: 2025/12/29
- name: (URB-21) HMRC banner - Guidance CXD 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_MTD_for_income_tax
  page_paths:
    # frontend
    - /guidance/find-software-thats-compatible-with-making-tax-digital-for-income-tax
    - /guidance/check-if-youre-eligible-for-making-tax-digital-for-income-tax
    - /guidance/work-out-your-qualifying-income-for-making-tax-digital-for-income-tax
    - /guidance/find-software-that-works-with-making-tax-digital-for-income-tax
    - /government/collections/making-tax-digital-for-income-tax-for-businesses-step-by-step
    # government-frontend
    - /guidance/use-making-tax-digital-for-income-tax
  start_date: 2025/12/01
  end_date: 2025/12/29
- name: (URB-24) HMRC banner - Guidance CXD 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Working_for_yourself
  page_paths:
    # frontend
    - /working-for-yourself
  start_date: 2025/12/01
  end_date: 2026/01/19
- name: (URB-24) HMRC banner - Guidance CXD 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Check_additional_income_tax
  page_paths:
    # frontend
    - /check-additional-income-tax
  start_date: 2025/12/01
  end_date: 2026/01/19
- name: (URB-24) HMRC banner - Guidance CXD 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Tell_HMRC_about_income_from_online_platforms
  page_paths:
    # frontend
    - /guidance/check-if-you-need-to-tell-hmrc-about-your-income-from-online-platforms
  start_date: 2025/12/01
  end_date: 2026/01/19
- name: (URB-24) HMRC banner - Guidance CXD 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Tell_HMRC_new_job_or_more_than_one_job
  page_paths:
    # frontend
    - /guidance/tell-hmrc-if-you-have-a-new-job-or-more-than-one-job
  start_date: 2025/12/01
  end_date: 2026/01/19
- name: (URB-25) App banner 2025/12/05
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://surveys.publishing.service.gov.uk/s/ST7P6Y/
  page_paths:
    # frontend
    - /vehicle-tax-rate-tables
    - /child-benefit-16-19
    - /income-tax-rates
    - /tax-free-childcare
    - /driving-test
    - /guidance/download-the-hmrc-app
    - /child-benefit
    - /what-different-qualification-levels-mean/list-of-qualification-levels
    - /government/organisations/land-registry
    - /child-maintenance-service
    - /take-practice-theory-test
    - /photos-for-passports
    - /fishing-licences
    - /theory-test/revision-and-practice
    - /maternity-pay-leave/pay
    - /vehicle-tax-rate-tables/rates-for-cars-registered-on-or-after-1-march-2001
    - /driving-licence-codes
    - /self-assessment-tax-returns
    - /carers-allowance
    - /government/organisations/department-for-work-pensions
  start_date: 2025/12/05
  end_date: 2026/01/02
- name: (URB-20) HMRC banner - Manuals 2025/12/09
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://forms.office.com/e/c4LPez4F25?origin=lprLink
  page_paths:
    # government-frontend
    - /hmrc-internal-manuals/partnership-manual
    - /hmrc-internal-manuals/partnership-manual/pm134200
    - /hmrc-internal-manuals/partnership-manual/pm137000
  start_date: 2025/12/09
  end_date: 2026/01/06
- name: (URB-19) HMRC banner - Guidance CXD 2025/12/08
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Check_Employment_Status
  page_paths:
    # frontend
    - /guidance/check-employment-status-for-tax
  start_date: 2025/12/09
  end_date: 2026/02/02
