# Check README.md for how to format this file
banners:
- name: (URB-19) HMRC banner - Guidance CXD 2025/12/08
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Check_Employment_Status
  page_paths:
    # frontend
    - /guidance/check-employment-status-for-tax
  start_date: 2025/12/08
  end_date: 2026/02/02
- name: (URB-23) HMRC banner - Guidance CXD 2025/12/11
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CEST_contracts_conditions
  page_paths:
    # frontend
    - /employment-contracts-and-conditions
  start_date: 2025/12/11
  end_date: 2026/02/05
- name: (URB-23) HMRC banner - Guidance CXD 2025/12/11
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CEST_Construction
  page_paths:
    # frontend
    - /what-is-the-construction-industry-scheme
  start_date: 2025/12/11
  end_date: 2026/02/05
- name: (URB-23) HMRC banner - Guidance CXD 2025/12/11
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CEST_limited_company_rules
  page_paths:
    # frontend
    - /employment-agencies-and-businesses/limited-company-contractors-and-opting-out-of-the-rules
  start_date: 2025/12/11
  end_date: 2026/02/05
- name: (URB-23) HMRC banner - Guidance CXD 2025/12/11
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CEST_recruiting
  page_paths:
    # collections
    - /browse/employing-people/recruiting-hiring
  start_date: 2025/12/11
  end_date: 2026/02/05
- name: (URB-23) HMRC banner - Guidance CXD 2025/12/11
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CEST_Employer_responsibilities
  page_paths:
    # frontend
    - /contract-types-and-employer-responsibilities
  start_date: 2025/12/11
  end_date: 2026/02/05
- name: (URB-26) HMRC banner - Policy 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Off_Payroll_Working_Agencies
  page_paths:
    # frontend
    - /guidance/off-payroll-working-for-agencies
  start_date: 2025/12/18
  end_date: 2026/01/15
- name: (URB-26) HMRC banner - Policy 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Understanding_Off_Payroll_Working_In_IR35
  page_paths:
    # frontend
    - /guidance/understanding-off-payroll-working-ir35
  start_date: 2025/12/18
  end_date: 2026/01/15
- name: (URB-26) HMRC banner - Policy 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Off_Payroll_Working_Rules
  page_paths:
    # frontend
    - /guidance/fee-payer-responsibilities-under-the-off-payroll-working-rules
  start_date: 2025/12/18
  end_date: 2026/01/15
- name: (URB-26) HMRC banner - Policy 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Off_Payroll_Working_For_Intermediaries_And_Contractors
  page_paths:
    # frontend
    - /guidance/off-payroll-working-for-intermediaries-and-contractors-providing-services-to-small-clients-in-the-private-sector
  start_date: 2025/12/18
  end_date: 2026/01/15
- name: (URB-26) HMRC banner - Policy 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Off_Payroll_Working_For_Intermediaries_And_Contractors_Private_Sector_Medium_Large_Clients
  page_paths:
    # frontend
    - /guidance/off-payroll-working-for-intermediaries-and-contractors-providing-services-to-the-public-sector-or-medium-and-large-clients-in-the-private-sector
  start_date: 2025/12/18
  end_date: 2026/01/15
- name: (URB-26) HMRC banner - Policy 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Check_Employment_Status_Hair_and_Beauty
  page_paths:
    # frontend
    - /guidance/check-employment-status-if-you-work-in-hair-and-beauty
  start_date: 2025/12/18
  end_date: 2026/01/15
- name: (URB-26) HMRC banner - Policy 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Off_Payroll_Working_IR35_Detailed_Information
  page_paths:
    # frontend
    - /government/collections/off-payroll-working-ir35-detailed-information
  start_date: 2025/12/18
  end_date: 2026/01/15
- name: (URB-26) HMRC banner - Policy 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Employed_or_Self_Employed
  page_paths:
    # frontend
    - /government/collections/employed-or-self-employed
  start_date: 2025/12/18
  end_date: 2026/01/15
- name: (URB-28) HMRC banner 2026/01/05
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CT_Guidance_TAD
  page_paths:
    # frontend
    - /pay-corporation-tax
    - /file-your-company-accounts-and-tax-return
    - /running-a-limited-company
    - /running-a-limited-company/taking-money-out-of-a-limited-company
    - /corporation-tax-rates
    - /guidance/company-expenses-you-can-deduct-before-paying-corporation-tax
    # collections
    - /set-up-limited-company
    # smartanswers
    - /next-steps-for-your-business
  start_date: 2026/01/05
  end_date: 2026/02/02
- name: (URB-29) HMRC banner 2026/01/05
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Partnerships2_TAD
  page_paths:
    # frontend
    - /guidance/register-a-partner-for-self-assessment-and-class-2-national-insurance
    - /government/publications/self-assessment-partnership-tax-return-sa800
    - /guidance/changes-to-reporting-income-from-self-employment-and-partnerships
    - /government/publications/self-assessment-partnership-uk-property-sa801
    - /guidance/register-a-partner-for-self-assessment-if-theyre-not-an-individual
  start_date: 2026/01/05
  end_date: 2026/02/02
- name: (URB-31) eVisa banner 2026/01/14
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://surveys.publishing.service.gov.uk/s/WI1UXK/
  page_paths:
    # frontend
    - /evisa
    - /evisa/set-up-ukvi-account
    - /evisa/view-evisa-get-share-code-prove-immigration-status
    - /evisa/travel-with-evisa
    - /evisa/report-error-evisa
    #collections
    - /browse/visas-immigration
    - /browse/visas-immigration/work-visas
    - /browse/visas-immigration/student-visas
    - /browse/visas-immigration/family-visas
    - /browse/visas-immigration/settle-in-the-uk
    - /browse/visas-immigration/eu-eea-swiss
  start_date: 2026/01/14
  end_date: 2026/02/04
