# Check README.md for how to format this file
banners:
- name: HMRC banner - Simple Assessment PAYE CI Request 25/10/17
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Tax_On_Pension
  page_paths:
    # frontend
    - /tax-on-pension
  start_date: 2025/10/17
  end_date: 2025/12/12
- name: HMRC banner - Simple Assessment PAYE CI Request 25/10/17
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Check_Simple_Assessment
  page_paths:
    # frontend
    - /check-simple-assessment
  start_date: 2025/10/17
  end_date: 2025/12/12
- name: HMRC banner - Simple Assessment PAYE CI Request 25/10/17
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Simple_Assessment
  page_paths:
    # frontend
    - /simple-assessment
  start_date: 2025/10/17
  end_date: 2025/12/12
- name: HMRC banner - Simple Assessment PAYE CI Request 25/10/17
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Apply_Tax_Free_Interest_On_Savings
  page_paths:
    # frontend
    - /apply-tax-free-interest-on-savings
  start_date: 2025/10/17
  end_date: 2025/12/12
- name: HMRC banner - CXD Guidance 2025/11/20
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Partnerships2_TAD
  page_paths:
    # frontend
    - /set-up-business-partnership
    - /set-up-business-partnership/register-partnership-with-hmrc
    - /guidance/register-a-partnership-for-self-assessment
    - /guidance/register-a-partner-for-self-assessment-and-class-2-national-insurance
    - /government/publications/self-assessment-partnership-full-sa104f
    - /government/publications/self-assessment-partnership-uk-property-sa801
    - /government/publications/self-assessment-partnership-tax-return-sa800
  start_date: 2025/11/20
  end_date: 2025/12/25
- name: (URB-21) HMRC banner - Guidance CXD 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_MTD_for_income_tax
  page_paths:
    # frontend
    - /guidance/find-software-thats-compatible-with-making-tax-digital-for-income-tax
    - /government/collections/making-tax-digital-for-income-tax-for-businesses-step-by-step
    - /government/collections/making-tax-digital-for-income-tax
    - /government/collections/making-tax-digital-for-income-tax-as-an-agent-step-by-step
    # government-frontend
    - /guidance/use-making-tax-digital-for-income-tax
  start_date: 2025/12/01
  end_date: 2025/12/29
- name: (URB-24) HMRC banner - Guidance CXD 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Working_for_yourself
  page_paths:
    # frontend
    - /working-for-yourself
  start_date: 2025/12/01
  end_date: 2026/01/19
- name: (URB-24) HMRC banner - Guidance CXD 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Check_additional_income_tax
  page_paths:
    # frontend
    - /check-additional-income-tax
  start_date: 2025/12/01
  end_date: 2026/01/19
- name: (URB-24) HMRC banner - Guidance CXD 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Tell_HMRC_about_income_from_online_platforms
  page_paths:
    # frontend
    - /guidance/check-if-you-need-to-tell-hmrc-about-your-income-from-online-platforms
  start_date: 2025/12/01
  end_date: 2026/01/19
- name: (URB-24) HMRC banner - Guidance CXD 2025/12/01
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Tell_HMRC_new_job_or_more_than_one_job
  page_paths:
    # frontend
    - /guidance/tell-hmrc-if-you-have-a-new-job-or-more-than-one-job
  start_date: 2025/12/01
  end_date: 2026/01/19
- name: (URB-20) HMRC banner - Manuals 2025/12/09
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://forms.office.com/e/c4LPez4F25?origin=lprLink
  page_paths:
    # government-frontend
    - /hmrc-internal-manuals/partnership-manual
    - /hmrc-internal-manuals/partnership-manual/pm134200
    - /hmrc-internal-manuals/partnership-manual/pm137000
  start_date: 2025/12/09
  end_date: 2026/01/06
- name: (URB-19) HMRC banner - Guidance CXD 2025/12/08
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_Check_Employment_Status
  page_paths:
    # frontend
    - /guidance/check-employment-status-for-tax
  start_date: 2025/12/08
  end_date: 2026/02/02
- name: (URB-22) HMRC banner - CXD CY 2025/12/01
  suggestion_text: "Helpwch i wella GOV.UK"
  suggestion_link_text: "Cofrestrwch i gymryd rhan mewn ymchwil defnyddwyr"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_cyfrif-treth-personol&Q_Language=CY
  page_paths:
    # frontend
    - /cyfrif-treth-personol
  start_date: 2025/12/01
  end_date: 2025/12/29
- name: (URB-22) HMRC banner - CXD CY 2025/12/01
  suggestion_text: "Helpwch i wella GOV.UK"
  suggestion_link_text: "Cofrestrwch i gymryd rhan mewn ymchwil defnyddwyr"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_mewngofnodi-cofrestru-gwasanaethau-ar-lein-cthef&Q_Language=CY
  page_paths:
    # frontend
    - /mewngofnodi-cofrestru-gwasanaethau-ar-lein-cthef
  start_date: 2025/12/01
  end_date: 2025/12/29
- name: (URB-22) HMRC banner - CXD CY 2025/12/01
  suggestion_text: "Helpwch i wella GOV.UK"
  suggestion_link_text: "Cofrestrwch i gymryd rhan mewn ymchwil defnyddwyr"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_treth-incwm-hunanasesiad-a-mwy&Q_Language=CY
  page_paths:
    # frontend
    - /find-hmrc-contacts/treth-incwm-hunanasesiad-a-mwy
  start_date: 2025/12/01
  end_date: 2025/12/29
- name: (URB-22) HMRC banner - CXD CY 2025/12/01
  suggestion_text: "Helpwch i wella GOV.UK"
  suggestion_link_text: "Cofrestrwch i gymryd rhan mewn ymchwil defnyddwyr"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_cyfrif-gofal-plant&Q_Language=CY
  page_paths:
    # frontend
    - /mewngofnodi-ir-cyfrif-gofal-plant
  start_date: 2025/12/01
  end_date: 2025/12/29
- name: (URB-22) HMRC banner - CXD CY 2025/12/01
  suggestion_text: "Helpwch i wella GOV.UK"
  suggestion_link_text: "Cofrestrwch i gymryd rhan mewn ymchwil defnyddwyr"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_download-the-hmrc-app.cy&Q_Language=CY
  page_paths:
    # frontend
    - /guidance/download-the-hmrc-app.cy
  start_date: 2025/12/01
  end_date: 2025/12/29
- name: (URB-23) HMRC banner - Guidance CXD 2025/12/11
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CEST_contracts_conditions
  page_paths:
    # frontend
    - /employment-contracts-and-conditions
  start_date: 2025/12/11
  end_date: 2026/02/05
- name: (URB-23) HMRC banner - Guidance CXD 2025/12/11
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CEST_Construction
  page_paths:
    # frontend
    - /what-is-the-construction-industry-scheme
  start_date: 2025/12/11
  end_date: 2026/02/05
- name: (URB-23) HMRC banner - Guidance CXD 2025/12/11
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CEST_limited_company_rules
  page_paths:
    # frontend
    - /employment-agencies-and-businesses/limited-company-contractors-and-opting-out-of-the-rules
  start_date: 2025/12/11
  end_date: 2026/02/05
- name: (URB-23) HMRC banner - Guidance CXD 2025/12/11
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CEST_recruiting
  page_paths:
    # collections
    - /browse/employing-people/recruiting-hiring
  start_date: 2025/12/11
  end_date: 2026/02/05
- name: (URB-23) HMRC banner - Guidance CXD 2025/12/11
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_CEST_Employer_responsibilities
  page_paths:
    # frontend
    - /contract-types-and-employer-responsibilities
  start_date: 2025/12/11
  end_date: 2026/02/05
- name: (URB-27) HMRC banner - Flat Rate Scheme 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_MTD_VAT_Flat_rate_scheme
  page_paths:
    # frontend
    - /vat-flat-rate-scheme
    - /vat-flat-rate-scheme/leaving-the-scheme
    - /vat-flat-rate-scheme/if-your-circumstances-change
    - /guidance/flat-rate-scheme-for-small-businesses-vat-notice-733--2
  start_date: 2025/12/15
  end_date: 2026/01/12
- name: (URB-27) HMRC banner - Reporting 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_MTD_VAT_Reporting
  page_paths:
    # frontend
    - /charge-reclaim-record-vat
    - /charge-reclaim-record-vat/when-not-to-charge-vat
  start_date: 2025/12/15
  end_date: 2026/01/12
- name: (URB-27) HMRC banner - Misc Banner 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_MTD_VAT_Misc
  page_paths:
    # frontend
    - /guidance/vat-exemption-and-partial-exemption
    - /guidance/partial-exemption-vat-notice-706
    - /guidance/vat-how-to-work-out-your-place-of-supply-of-services
    - /guidance/vat-place-of-supply-of-services-notice-741a
  start_date: 2025/12/15
  end_date: 2026/01/12
- name: (URB-27) HMRC banner - Registration 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_MTD_VAT_Registration
  page_paths:
    # frontend
    - /government/publications/vat-notice-7001-should-i-be-registered-for-vat/vat-notice-7001-should-i-be-registered-for-vat
  start_date: 2025/12/15
  end_date: 2026/01/12
- name: (URB-27) HMRC banner - Deregistration 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_MTD_VAT_De-registration
  page_paths:
    # frontend
    - /register-for-vat/cancel-your-registration  
  start_date: 2025/12/15
  end_date: 2026/01/12
- name: (URB-27) HMRC banner - Payments 2025/12/15
  suggestion_text: "Help improve GOV.UK"
  suggestion_link_text: "Sign up to take part in user research (opens in a new tab)"
  survey_url: https://survey.take-part-in-research.service.gov.uk/jfe/form/SV_74GjifgnGv6GsMC?Source=BannerList_HMRC_MTD_VAT_Payments
  page_paths:
    # frontend
    - /pay-vat
    - /pay-vat/direct-debit
    - /pay-vat/pay-using-another-payment-method
    - /guidance/vat-payments-on-account
    - /guidance/vat-imports-acquisitions-and-purchases-from-abroad
    - /guidance/how-late-payment-penalties-work-if-you-pay-vat-late
  start_date: 2025/12/15
  end_date: 2026/01/12
